# Generated by Django 4.0.5 on 2023-02-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('quote', models.CharField(max_length=10)),
                ('first_created', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
