# Generated by Django 4.0.5 on 2023-03-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0002_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='company',
            field=models.CharField(default='Temporarily Unavailable', max_length=50),
            preserve_default=False,
        ),
    ]
