# Generated by Django 4.0.5 on 2023-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0003_watch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
