# Generated by Django 4.0.5 on 2023-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0005_purchase_sell_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='earnedTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
