# Generated by Django 4.0.5 on 2023-03-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0006_share_earnedtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='label',
            field=models.CharField(default='bought', max_length=50),
        ),
        migrations.AddField(
            model_name='sell',
            name='label',
            field=models.CharField(default='sold', max_length=50),
        ),
    ]
